In [19]:
import numpy as np
import pandas as pd

In [20]:
import ast

In [21]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

# Understanding Data

In [22]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [23]:
movies.shape

(4803, 20)

In [24]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [25]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
credits.shape

(4803, 4)

# Merging Both the DataSets

In [27]:
movies = movies.merge(credits, on='title')

In [28]:
movies = movies[['movie_id',
                 'title',
                 'overview',
                 'genres',
                 'keywords',
                 'cast',
                 'crew']]

In [29]:
movies.dropna(inplace = True)

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
movies.shape

(4806, 7)

In [32]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [33]:
movies.dropna(inplace = True)

# Data Preprocessing

In [34]:
def convert(obj):
    L = []

    for i in ast.literal_eval(obj):
        L.append(i['name'])

    return L

In [35]:
def convert3(obj):
    L = []
    counter = 0

    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break

    return L

In [36]:
def fetch_director(obj):
    L = []

    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break

    return L

In [37]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)
movies['cast'] = movies['cast'].apply(convert3)
movies['crew'] = movies['crew'].apply(fetch_director)

In [38]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [39]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])

movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [40]:
movies['tags'] = movies['overview'] + 3*movies['genres'] + 2*movies['keywords'] + 1*movies['cast'] + 2*movies['crew']

In [41]:
new_df = movies[['movie_id','title','tags']]

In [42]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [43]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_926/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [44]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_926/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

# **Stemming**

In [45]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [46]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [47]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_926/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [48]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [49]:
new_df.shape

(4806, 3)

# **TF - IDF**

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words='english',
    ngram_range=(1, 2),   # captures phrases like "science fiction"
    min_df=2,
    max_df=0.9
)

vectors = tfidf.fit_transform(new_df['tags'])

In [64]:
vectors.shape

(4806, 10000)

Similarity

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
tf_idf_sim = cosine_similarity(vectors)

In [68]:
tf_idf_sim.shape

(4806, 4806)

In [70]:
sorted(list(enumerate(tf_idf_sim[0])),
       reverse=True,
       key=lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (1192, np.float64(0.258693048058571)),
 (47, np.float64(0.2437255807917144)),
 (3496, np.float64(0.24330877960576197)),
 (1654, np.float64(0.2294927994579481)),
 (1934, np.float64(0.22449410138960885)),
 (46, np.float64(0.2239223137961397)),
 (2405, np.float64(0.21310223238735346)),
 (14, np.float64(0.2105309854469178)),
 (260, np.float64(0.20672058292071777)),
 (870, np.float64(0.20631311990251286)),
 (2071, np.float64(0.20524035569474086)),
 (305, np.float64(0.1989022028908296)),
 (3728, np.float64(0.19275566685878695)),
 (1827, np.float64(0.18905436791620403)),
 (859, np.float64(0.1865428016577415)),
 (813, np.float64(0.1809171644251253)),
 (786, np.float64(0.17430850972827497)),
 (931, np.float64(0.17424700775599034)),
 (1613, np.float64(0.1736665654945187)),
 (61, np.float64(0.17277814928502688)),
 (1087, np.float64(0.17190112958367637)),
 (4, np.float64(0.17157194321808866)),
 (661, np.float64(0.17139796296733664)),
 (1297, np.float64(0.17103140493010793)),
 (1938, np.float64(0.1708625813796398)),
 (322, np.float64(0.1672118301230977)),
 (72, np.float64(0.16618946641721422)),
 (2329, np.float64(0.16575843829497688)),
 (4046, np.float64(0.16316437322059554)),
 (2165, np.float64(0.1617902446464676)),
 (539, np.float64(0.15999826839957673)),
 (1804, np.float64(0.15875755433866295)),
 (2852, np.float64(0.15848284208158364)),
 (420, np.float64(0.15781799404787147)),
 (582, np.float64(0.1573292023022543)),
 (36, np.float64(0.15732065283760213)),
 (2657, np.float64(0.15592253911844)),
 (507, np.float64(0.15514934626628685)),
 (419, np.float64(0.15202490852214645)),
 (778, np.float64(0.15182587578191642)),
 (1193, np.float64(0.14946322413163682)),
 (278, np.float64(0.14930717899784046)),
 (238, np.float64(0.1485976976406182)),
 (168, np.float64(0.14797543687759668)),
 (838, np.float64(0.14734244417546538)),
 (654, np.float64(0.14224833553679345)),
 (172, np.float64(0.1421548818410105)),
 (3210, np.float64(0.14191360048919963)),
 (1202, np.float64(0.14184683350724592)),
 (3997, np.float64(0.14027176430302565)),
 (3536, np.float64(0.14005910203177988)),
 (184, np.float64(0.13995820778659104)),
 (4403, np.float64(0.13949274160243003)),
 (74, np.float64(0.13799421119205094)),
 (1342, np.float64(0.1377382844832249)),
 (84, np.float64(0.13770060908190002)),
 (581, np.float64(0.13728255717975407)),
 (1941, np.float64(0.1371740594984472)),
 (126, np.float64(0.13694270913444623)),
 (56, np.float64(0.13680652007746513)),
 (1260, np.float64(0.1365551549687348)),
 (91, np.float64(0.13640866097623153)),
 (3734, np.float64(0.13598217551785252)),
 (3781, np.float64(0.13576775749259914)),
 (369, np.float64(0.1352320512522265)),
 (2446, np.float64(0.13455864235518805)),
 (1440, np.float64(0.13441647698854586)),
 (627, np.float64(0.13424423112258135)),
 (2319, np.float64(0.13422464001210271)),
 (2494, np.float64(0.13280290821246743)),
 (1304, np.float64(0.13270734884051008)),
 (577, np.float64(0.1323116873595443)),
 (208, np.float64(0.13139003292743512)),
 (207, np.float64(0.1303654446548775)),
 (111, np.float64(0.12841702355360235)),
 (9, np.float64(0.12822708954457246)),
 (2392, np.float64(0.12819795205515722)),
 (2129, np.float64(0.12762225422582057)),
 (158, np.float64(0.12721040688758367)),
 (38, np.float64(0.12617405381336266)),
 (83, np.float64(0.12609645235895856)),
 (1214, np.float64(0.12462858913871994)),
 (1533, np.float64(0.12428433772385623)),
 (2997, np.float64(0.12409233748999064)),
 (182, np.float64(0.12386170017960552)),
 (978, np.float64(0.12372622694035097)),
 (4336, np.float64(0.12232334912026635)),
 (17, np.float64(0.12198810456281688)),
 (3307, np.float64(0.12100320919309057)),
 (2869, np.float64(0.12051020266327063)),
 (2594, np.float64(0.12046513770365476)),
 (1278, np.float64(0.12020264555832136)),
 (52, np.float64(0.11921342339094808)),
 (4121, np.float64(0.11869881301527954)),
 (1288, np.float64(0.11857855129868106)),
 (2200, np.float64(0.11772297293472984)),
 (193, np.float64(0.11744315712273852)),
 (7, np.float64(0.11737621675705298)),
 (426, np.float64(0.11730116217094527)),
 (4329, np.float64(0.1172673040029989)),
 (2969, np.float64(0.11710447082438295)),
 (836, np.float64(0.11649704347277448)),
 (342, np.float64(0.11637069296545154)),
 (1392, np.float64(0.11627763675019195)),
 (108, np.float64(0.11554820798409726)),
 (31, np.float64(0.1154851125447217)),
 (2899, np.float64(0.11515800297865081)),
 (541, np.float64(0.11501626965915727)),
 (483, np.float64(0.11494108143447442)),
 (102, np.float64(0.1145848571042877)),
 (85, np.float64(0.11456100434421598)),
 (643, np.float64(0.1135529649142425)),
 (30, np.float64(0.11278404261230733)),
 (1295, np.float64(0.11261698389789697)),
 (2580, np.float64(0.11256698081724566)),
 (3160, np.float64(0.11246201450618343)),
 (1176, np.float64(0.11197374420152884)),
 (1156, np.float64(0.11172478389594856)),
 (4190, np.float64(0.1112136627241593)),
 (4405, np.float64(0.111001558151166)),
 (232, np.float64(0.11073792685391036)),
 (3216, np.float64(0.11051980760154635)),
 (472, np.float64(0.11020863659764762)),
 (150, np.float64(0.10991346861747286)),
 (473, np.float64(0.10939076334612605)),
 (50, np.float64(0.10929129587347132)),
 (2116, np.float64(0.10921021647037496)),
 (206, np.float64(0.10920098054441635)),
 (1231, np.float64(0.10914756138858629)),
 (2264, np.float64(0.10897326483804305)),
 (898, np.float64(0.10869155339911617)),
 (35, np.float64(0.10863777676803066)),
 (311, np.float64(0.1079578094835731)),
 (3804, np.float64(0.10761203515560151)),
 (513, np.float64(0.10742861617028865)),
 (1645, np.float64(0.1066184306454227)),
 (935, np.float64(0.10641498201127225)),
 (121, np.float64(0.10622385236721407)),
 (2391, np.float64(0.10603042318890708)),
 (279, np.float64(0.10564571067208504)),
 (2068, np.float64(0.10562182386330149)),
 (3441, np.float64(0.10520739910545243)),
 (129, np.float64(0.10495985916860287)),
 (12, np.float64(0.10477860934366258)),
 (1916, np.float64(0.10455247438803117)),
 (1267, np.float64(0.10421866000230741)),
 (10, np.float64(0.10410505357164562)),
 (2249, np.float64(0.10405718283254431)),
 (486, np.float64(0.10372221536965166)),
 (972, np.float64(0.10363570467673547)),
 (1086, np.float64(0.1035165104338695)),
 (1986, np.float64(0.10340645600591192)),
 (1669, np.float64(0.10319354765538667)),
 (2260, np.float64(0.10295618453697486)),
 (3233, np.float64(0.10265490766993784)),
 (4008, np.float64(0.1026205127267894)),
 (23, np.float64(0.1022856833471999)),
 (1475, np.float64(0.10223687653540706)),
 (2827, np.float64(0.10208900310399603)),
 (1660, np.float64(0.10205072366904813)),
 (1320, np.float64(0.10203089629316808)),
 (2782, np.float64(0.10191541692311397)),
 (1140, np.float64(0.10175008943978045)),
 (332, np.float64(0.10143126361114138)),
 (27, np.float64(0.10134431505814104)),
 (754, np.float64(0.10108775017057495)),
 (1, np.float64(0.10080543295437859)),
 (495, np.float64(0.10074209083170449)),
 (20, np.float64(0.1007167740125868)),
 (1200, np.float64(0.10050174374837681)),
 (3407, np.float64(0.09975251535471316)),
 (2374, np.float64(0.09972582195917405)),
 (107, np.float64(0.09963170881198864)),
 (373, np.float64(0.09936783409674213)),
 (1069, np.float64(0.09935805751715823)),
 (3447, np.float64(0.09933311146337784)),
 (1275, np.float64(0.09910966900227972)),
 (4502, np.float64(0.09902411025741643)),
 (2709, np.float64(0.099002494741453)),
 (19, np.float64(0.0988229477916962)),
 (2682, np.float64(0.09822767457236804)),
 (86, np.float64(0.09799248139544392)),
 (3091, np.float64(0.09788042254264852)),
 (1002, np.float64(0.09757291745404903)),
 (1752, np.float64(0.0974377353113704)),
 (94, np.float64(0.09732834691584308)),
 (1880, np.float64(0.09732712821278423)),
 (1273, np.float64(0.09728545938336082)),
 (1274, np.float64(0.09676790676907143)),
 (1154, np.float64(0.09673308098856453)),
 (331, np.float64(0.09661676906994394)),
 (572, np.float64(0.09658927254185094)),
 (41, np.float64(0.0964474705980954)),
 (131, np.float64(0.09634367516487047)),
 (174, np.float64(0.09627414416015777)),
 (1084, np.float64(0.09624332994196344)),
 (330, np.float64(0.0958227546097144)),
 (127, np.float64(0.09520700693081081)),
 (973, np.float64(0.09513263097471321)),
 (169, np.float64(0.09495764830679519)),
 (5, np.float64(0.0949362567705467)),
 (300, np.float64(0.09490791401975834)),
 (329, np.float64(0.09485575224026083)),
 (16, np.float64(0.0945199847539363)),
 (199, np.float64(0.0943383411689972)),
 (187, np.float64(0.09417762367791604)),
 (2476, np.float64(0.09411496098632335)),
 (466, np.float64(0.09351509448823153)),
 (2131, np.float64(0.09300332327779628)),
 (799, np.float64(0.09281109862168102)),
 (3606, np.float64(0.09274260905312927)),
 (1493, np.float64(0.09251786078825737)),
 (543, np.float64(0.09247993621780587)),
 (1435, np.float64(0.09221092142541623)),
 (1035, np.float64(0.09219429478011143)),
 (341, np.float64(0.09149386091887118)),
 (587, np.float64(0.09135860941016832)),
 (3006, np.float64(0.09086983832053774)),
 (3053, np.float64(0.09084613993522067)),
 (1688, np.float64(0.09050031494953654)),
 (777, np.float64(0.09022568949126039)),
 (242, np.float64(0.08999187536935924)),
 (3626, np.float64(0.08958502500326271)),
 (3905, np.float64(0.08940822302070281)),
 (3374, np.float64(0.08918183510469507)),
 (149, np.float64(0.08901438952513738)),
 (262, np.float64(0.0888481020974058)),
 (97, np.float64(0.08825406450505291)),
 (410, np.float64(0.08823539011335937)),
 (266, np.float64(0.08805132122825146)),
 (2435, np.float64(0.08784405745758772)),
 (160, np.float64(0.08767045754411994)),
 (4468, np.float64(0.08751038506409653)),
 (1717, np.float64(0.0872619950212854)),
 (22, np.float64(0.08708891346573758)),
 (4331, np.float64(0.08693513289355448)),
 (3671, np.float64(0.08692173633264452)),
 (618, np.float64(0.08658775957791774)),
 (1271, np.float64(0.08652051369347691)),
 (1030, np.float64(0.08642171737601498)),
 (1013, np.float64(0.08638638483140494)),
 (309, np.float64(0.08627232509559168)),
 (67, np.float64(0.08624429388136072)),
 (379, np.float64(0.08607283342838004)),
 (1723, np.float64(0.08597293314024448)),
 (220, np.float64(0.08596375405909826)),
 (1353, np.float64(0.08563511717022255)),
 (1414, np.float64(0.08560068910446846)),
 (8, np.float64(0.08548726481257934)),
 (612, np.float64(0.08543984514998074)),
 (4196, np.float64(0.08536974353827491)),
 (557, np.float64(0.08524710599276637)),
 (1585, np.float64(0.08516033496186914)),
 (292, np.float64(0.08481194281049005)),
 (591, np.float64(0.08474801853474295)),
 (3325, np.float64(0.08463320348439116)),
 (362, np.float64(0.08450478859719424)),
 (1327, np.float64(0.08450451238224554)),
 (1610, np.float64(0.0844949717595141)),
 (18, np.float64(0.08419110520758638)),
 (1920, np.float64(0.08366339418769583)),
 (403, np.float64(0.0834793623144642)),
 (2756, np.float64(0.08340751767424473)),
 (457, np.float64(0.08339548294579954)),
 (98, np.float64(0.0832794414188942)),
 (3331, np.float64(0.08302742691950019)),
 (3320, np.float64(0.08292366128416088)),
 (4268, np.float64(0.082854828612938)),
 (1992, np.float64(0.08227435155878088)),
 (920, np.float64(0.08212619261984702)),
 (3620, np.float64(0.08195819303160368)),
 (157, np.float64(0.08190808189975984)),
 (3779, np.float64(0.08155790223601087)),
 (59, np.float64(0.08143897050757418)),
 (28, np.float64(0.08141095946504771)),
 (241, np.float64(0.08105671464205368)),
 (1299, np.float64(0.08102897682448107)),
 (1401, np.float64(0.08083181596316096)),
 (1338, np.float64(0.08029254181444426)),
 (2968, np.float64(0.08024936685123676)),
 (1737, np.float64(0.08024805296261708)),
 (1029, np.float64(0.08019744905031184)),
 (138, np.float64(0.08016156972310118)),
 (134, np.float64(0.07973915864516065)),
 (2345, np.float64(0.07958857868105036)),
 (889, np.float64(0.07949768970370917)),
 (467, np.float64(0.07948682737173789)),
 (2727, np.float64(0.07944207970857019)),
 (4146, np.float64(0.07935033086113627)),
 (942, np.float64(0.07924285547402865)),
 (1570, np.float64(0.07915745711516654)),
 (2124, np.float64(0.07881534633581622)),
 (368, np.float64(0.07876200624640557)),
 (249, np.float64(0.07875512940000336)),
 (488, np.float64(0.07863415991708836)),
 (773, np.float64(0.07853238565717227)),
 (62, np.float64(0.07848753662634571)),
 (1697, np.float64(0.07826758985612225)),
 (784, np.float64(0.07798869278222736)),
 (21, np.float64(0.07774128854569429)),
 (223, np.float64(0.07767400819110626)),
 (3860, np.float64(0.07756153412460598)),
 (222, np.float64(0.07730365882196776)),
 (568, np.float64(0.0772875239560008)),
 (2816, np.float64(0.07717482946015569)),
 (3100, np.float64(0.07705441510946738)),
 (219, np.float64(0.07701059686162567)),
 (535, np.float64(0.07688808396868893)),
 (3426, np.float64(0.07677303448868625)),
 (595, np.float64(0.07664467617132566)),
 (449, np.float64(0.0765194836575642)),
 (359, np.float64(0.07650128818243046)),
 (95, np.float64(0.07631329624146696)),
 (294, np.float64(0.07631015084287959)),
 (1045, np.float64(0.07580636569895846)),
 (1257, np.float64(0.0754170994507017)),
 (1199, np.float64(0.07538863477326191)),
 (660, np.float64(0.07518330399862358)),
 (70, np.float64(0.0748233892868552)),
 (3618, np.float64(0.07481860527459176)),
 (412, np.float64(0.07472322611645424)),
 (476, np.float64(0.07464375030420527)),
 (1770, np.float64(0.07454960242318359)),
 (687, np.float64(0.07453569539369666)),
 (3980, np.float64(0.07440173881679363)),
 (583, np.float64(0.07430314536435453)),
 (1978, np.float64(0.07429095638707592)),
 (4320, np.float64(0.07427611476467694)),
 (151, np.float64(0.07426564258334273)),
 (1711, np.float64(0.07395494369628214)),
 (1083, np.float64(0.07378287923648658)),
 (1321, np.float64(0.07368495859075574)),
 (282, np.float64(0.07360783508493139)),
 (1449, np.float64(0.0733440790619007)),
 (755, np.float64(0.0730339762540208)),
 (487, np.float64(0.07282816606811152)),
 (307, np.float64(0.0727698049510921)),
 (977, np.float64(0.07276955581527723)),
 (2575, np.float64(0.07271248702801221)),
 (1442, np.float64(0.07267933379992465)),
 (2, np.float64(0.07263440977198428)),
 (438, np.float64(0.07246010455600005)),
 (26, np.float64(0.07221718858857945)),
 (3315, np.float64(0.07210292319015334)),
 (2280, np.float64(0.0719183035190746)),
 (3138, np.float64(0.07182268373956202)),
 (1635, np.float64(0.07177450730590329)),
 (2492, np.float64(0.07173673807690747)),
 (75, np.float64(0.07167977946809202)),
 (82, np.float64(0.07156574978043598)),
 (2758, np.float64(0.07144903472010347)),
 (461, np.float64(0.0714257246936645)),
 (505, np.float64(0.07132651680101958)),
 (1235, np.float64(0.07123307557467065)),
 (502, np.float64(0.07113819505069113)),
 (215, np.float64(0.0711368407171749)),
 (1617, np.float64(0.0709913916712359)),
 (167, np.float64(0.0709725465009717)),
 (81, np.float64(0.07084454184887728)),
 (3862, np.float64(0.07065401345957426)),
 (312, np.float64(0.07055809270855677)),
 (995, np.float64(0.07049700875860715)),
 (1894, np.float64(0.07049297650462343)),
 (617, np.float64(0.07035598183353295)),
 (922, np.float64(0.07025744988633575)),
 (2697, np.float64(0.07013342864003633)),
 (602, np.float64(0.07011110255226999)),
 (32, np.float64(0.06984526556203777)),
 (3524, np.float64(0.06974885190774116)),
 (732, np.float64(0.06966673426858921)),
 (319, np.float64(0.06956654808376048)),
 (1508, np.float64(0.06943211920662942)),
 (549, np.float64(0.06932491398273934)),
 (1989, np.float64(0.06929151387629387)),
 (197, np.float64(0.06908994954215239)),
 (243, np.float64(0.0689706018803116)),
 (1319, np.float64(0.06875885914490383)),
 (228, np.float64(0.06855344987016504)),
 (1000, np.float64(0.06836394281903578)),
 (4568, np.float64(0.06811547205362513)),
 (1619, np.float64(0.06780447617764264)),
 (939, np.float64(0.06756187475970236)),
 (422, np.float64(0.06752256267880434)),
 (2547, np.float64(0.06742620392949317)),
 (600, np.float64(0.06740836300290856)),
 (1379, np.float64(0.0672906823352487)),
 (664, np.float64(0.06727486797300719)),
 (579, np.float64(0.06716766342529783)),
 (263, np.float64(0.06716598047537303)),
 (80, np.float64(0.06706590716312594)),
 (2359, np.float64(0.06676166337189647)),
 (1080, np.float64(0.06675473390628459)),
 (276, np.float64(0.06657161267678671)),
 (4654, np.float64(0.06656833750169852)),
 (1218, np.float64(0.06651766713499145)),
 (224, np.float64(0.06637101343731758)),
 (105, np.float64(0.06636149403624635)),
 (4626, np.float64(0.0662918361734033)),
 (1430, np.float64(0.06628231473318646)),
 (3387, np.float64(0.066240818435403)),
 (2511, np.float64(0.06599787754451249)),
 (2641, np.float64(0.06596334278281082)),
 (2813, np.float64(0.06579505652016192)),
 (114, np.float64(0.06578643493857624)),
 (1441, np.float64(0.06572113085618175)),
 (3952, np.float64(0.06559609763401812)),
 (25, np.float64(0.06553533895724849)),
 (3145, np.float64(0.06511845405916131)),
 (1766, np.float64(0.06504901554170861)),
 (4623, np.float64(0.06499137344229017)),
 (503, np.float64(0.06493720590466302)),
 (540, np.float64(0.06492565396994679)),
 (2354, np.float64(0.064900564767998)),
 (4254, np.float64(0.06478250123247405)),
 (2163, np.float64(0.06476676065901411)),
 (3003, np.float64(0.06474816029826502)),
 (1761, np.float64(0.06473215217248018)),
 (3462, np.float64(0.06467418934837532)),
 (3135, np.float64(0.06453249835416625)),
 (164, np.float64(0.06450475118771343)),
 (191, np.float64(0.0643630509102263)),
 (239, np.float64(0.06420610686887673)),
 (3150, np.float64(0.06412410734320133)),
 (304, np.float64(0.06402142829489477)),
 (1856, np.float64(0.06397884817250332)),
 (4602, np.float64(0.06397397328206812)),
 (356, np.float64(0.06373719516543101)),
 (4077, np.float64(0.06371048075479832)),
 (490, np.float64(0.06351757125671992)),
 (2048, np.float64(0.0635082087248591)),
 (1571, np.float64(0.0633841094115976)),
 (3619, np.float64(0.06327078209893536)),
 (1682, np.float64(0.06306880431701392)),
 (791, np.float64(0.06305558182555766)),
 (578, np.float64(0.0630194699679635)),
 (2484, np.float64(0.06286453568943293)),
 (2207, np.float64(0.0627774361575797)),
 (831, np.float64(0.06277042106578666)),
 (1909, np.float64(0.06268238836499436)),
 (1094, np.float64(0.06250274318945416)),
 (1779, np.float64(0.062326705441280605)),
 (4179, np.float64(0.062209671842874056)),
 (800, np.float64(0.06216272762260737)),
 (1961, np.float64(0.06216107267446244)),
 (900, np.float64(0.061959770964442405)),
 (4453, np.float64(0.06190877793779676)),
 (1303, np.float64(0.06183017707848475)),
 (479, np.float64(0.06177049190444074)),
 (544, np.float64(0.06164172832492415)),
 (259, np.float64(0.061297908031830876)),
 (1828, np.float64(0.06125497017923588)),
 (1483, np.float64(0.06122919564998366)),
 (491, np.float64(0.061163973459649815)),
 (4228, np.float64(0.06083331139952421)),
 (2177, np.float64(0.06082567080322372)),
 (624, np.float64(0.0607750879657547)),
 (275, np.float64(0.06066470841851743)),
 (1556, np.float64(0.06045395435725889)),
 (3628, np.float64(0.060274398731884025)),
 (1054, np.float64(0.06019801693009244)),
 (4163, np.float64(0.06019405059643872)),
 (640, np.float64(0.060171881803363185)),
 (469, np.float64(0.0601114932090632)),
 (1325, np.float64(0.05997656562247204)),
 (1107, np.float64(0.05988763937359372)),
 (4566, np.float64(0.05986489810138028)),
 (2656, np.float64(0.05982856823836524)),
 (1829, np.float64(0.0597390243638687)),
 (415, np.float64(0.05970841741297806)),
 (4640, np.float64(0.059682768569837216)),
 (1291, np.float64(0.05955078421634974)),
 (1484, np.float64(0.05943887832353225)),
 (4316, np.float64(0.05924504808580405)),
 (2679, np.float64(0.05921834193203472)),
 (475, np.float64(0.05921520595813841)),
 (3933, np.float64(0.0591617483718144)),
 (1355, np.float64(0.05902248400938696)),
 (4016, np.float64(0.05883324202965745)),
 (290, np.float64(0.05877244338304227)),
 (411, np.float64(0.05875577852782127)),
 (691, np.float64(0.05874564078221092)),
 (1520, np.float64(0.058718248919708976)),
 (113, np.float64(0.058648041001666686)),
 (4357, np.float64(0.058645962387787166)),

In [71]:
def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = tf_idf_sim[movie_index]

    movies_list = sorted(list(enumerate(distances)),
                         reverse=True,
                         key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [72]:
recommend('Avatar')

Small Soldiers
Star Trek Into Darkness
Beastmaster 2: Through the Portal of Time
Dragonball Evolution
Sheena

# **Count Vectorizer**

In [73]:
#Vectorization

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors.shape

"""Similarity"""

from sklearn.metrics.pairwise import cosine_similarity

cv_similarity = cosine_similarity(vectors)

new_df[new_df['title'] == 'Avatar'].index[0]

list(enumerate(cv_similarity[0]))

sorted(list(enumerate(cv_similarity[0])),
       reverse=True,
       key=lambda x:x[1])

def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = cv_similarity[movie_index]

    movies_list = sorted(list(enumerate(distances)),
                         reverse=True,
                         key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

recommend('Avatar')

Jupiter Ascending
Small Soldiers
Ender's Game
The Time Machine
The Lovers

# **Sentence Transformer**

In [62]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
#-----------------------------
# 1. Load embedding model
# -----------------------------
model = SentenceTransformer('all-MiniLM-L6-v2')

# -----------------------------
# 2. Generate embeddings
# -----------------------------
embeddings = model.encode(new_df['tags'].tolist(), show_progress_bar=True)

# -----------------------------
# 3. Cosine similarity matrix
# -----------------------------
similarity = cosine_similarity(embeddings)

# -----------------------------
# 4. Index mapping
# -----------------------------
indices = pd.Series(new_df.index, index=new_df['title']).drop_duplicates()

# -----------------------------
# 5. Recommendation function
# -----------------------------
def recommend(movie_title, top_n=5):
    idx = indices[movie_title]

    sim_scores = list(enumerate(similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:top_n+1]

    return [new_df.iloc[i[0]]['title'] for i in sim_scores]

# -----------------------------
# 6. Example
# -----------------------------
print(recommend("Avatar"))

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/151 [00:00<?, ?it/s]

['Battle: Los Angeles', 'The Inhabited Island', 'The Day the Earth Stood Still', 'U.F.O.', 'Prometheus']

In [74]:
final_sim = (
    0.1 * cv_similarity +
    0.3 * tf_idf_sim +
    0.6 * similarity
)

In [75]:
def recommend(movie):
    idx = new_df[new_df['title'] == movie].index[0]

    scores = list(enumerate(final_sim[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    for i in scores:
        print(new_df.iloc[i[0]].title)

In [84]:
recommend("Titanic")

The Blue Lagoon
In the Heart of the Sea
Love in the Time of Cholera
Event Horizon
The Bounty

In [77]:
import pickle

In [78]:
pickle.dump(new_df, open('movies.pkl','wb'))

In [85]:
pickle.dump(final_sim, open('similarity.pkl','wb'))

In [80]:
API_KEY = "7f6deb75aa1f753c6aa8cb4e44ff1fa4"

In [81]:
import requests

In [82]:
movie_id = 19995

url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US"

response = requests.get(url)

data = response.json()

data

{'adult': False,
 'backdrop_path': '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
 'belongs_to_collection': {'id': 87096,
  'name': 'Avatar Collection',
  'poster_path': '/3C5brXxnBxfkeKWwA1Fh4xvy4wr.jpg',
  'backdrop_path': '/gxnvX9kF7RRUQYvB52dMLPgeJkt.jpg'},
 'budget': 237000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://www.avatar.com/movies/avatar',
 'id': 19995,
 'imdb_id': 'tt0499549',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'Avatar',
 'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
 'popularity': 36.6537,
 'poster_path': '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg',
 'production_companies': [{'id': 444,
   'logo_path': None,
   'name': 'Dune Entertainment',
   'origin_country': 'US'},
  {'id': 574,
   'logo_path': '/8wdmrfGcDx3TJxYiiDksLzAW4pB.png',
   'name': 'Lightstorm Entertainment',
   'origin_country': 'US'},
  {'id': 25,
   'logo_path': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
   'name': '20th Century Fox',
   'origin_country': 'US'},
  {'id': 133789,
   'logo_path': '/bJdeIb1ET3BkyodAASVDq1x3mls.png',
   'name': 'Ingenious Film Partners',
   'origin_country': 'GB'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'},
  {'iso_3166_1': 'GB', 'name': 'United Kingdom'}],
 'release_date': '2009-12-16',
 'revenue': 2923706026,
 'runtime': 162,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'},
  {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'}],
 'status': 'Released',
 'tagline': 'Enter the world of Pandora.',
 'title': 'Avatar',
 'video': False,
 'vote_average': 7.604,
 'vote_count': 33954}

In [83]:
def fetch_poster(movie_id):

    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US"

    data = requests.get(url)

    data = data.json()

    poster_path = data.get('poster_path')

    if poster_path:
        full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    else:
        # Return a placeholder image if poster_path is not available
        full_path = "https://via.placeholder.com/500x750?text=No+Poster+Available"

    return full_path

In [ ]:
fetch_poster(19995)

'https://image.tmdb.org/t/p/w500//gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg'

In [ ]:
def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:6]

    recommended_movies = []
    recommended_posters = []

    for i in movies_list:

        movie_id = new_df.iloc[i[0]].movie_id

        recommended_movies.append(new_df.iloc[i[0]].title)

        recommended_posters.append(fetch_poster(movie_id))

    return recommended_movies, recommended_posters

In [ ]:
movies, posters = recommend('Avatar')

movies

['Jupiter Ascending',
 'Small Soldiers',
 "Ender's Game",
 'The Time Machine',
 'The Lovers']

In [ ]:
from IPython.display import Image, display

for poster in posters:
    display(Image(url=poster))

In [ ]:
def fetch_reviews(movie_id):

    url = f"https://api.themoviedb.org/3/movie/{movie_id}/reviews?api_key={API_KEY}&language=en-US"

    data = requests.get(url)

    data = data.json()

    reviews = []

    for review in data.get('results', []):
        reviews.append(review['content'])

    return reviews

In [ ]:
reviews = fetch_reviews(19995)

len(reviews)
if reviews:
    print(reviews[0])
else:
    print("No reviews available for this movie.")

It's cinema Jim, but not as we know it.

So here it is then, what has been in gestation in James Cameron's mind for over 12 years finally hit the silver screen towards the back end of 2009. Made for gazillions amount of cash, Avatar went on to make a billion trillion in Worldwide receipts-and this before the rush rush release of DVD/BLU RAY sales are factored into the equation. The film, and all its technical wizardry, is quite simply a gargantuan piece of cinematic history. Released in 2d and 3d, and probably some other format that I'm forgetting, every advanced tool of the trade has been utilised by Cameron and his team to create what is now the ultimate popcorn blockbuster. Shame then, that away from the visual extravaganza the film is as shallow as this review will ultimately end up being.

No doubt about it, this is a joy for the eyes and ears, the minuscule details are wonderful and the colour positively pings from every frame. But in the eagerness to create such splendour they forgot to put any substance into the writing. This is plot simplicity. And even its messages, as Cameron smugly preaches his sermon from the pulpit, now seem old hat. Do we really need another boink over the head about eco invasion? Or a curt reminder of American infiltration into some land where motives are suspicious at best? No we don't really do we? Worse still is some of the dialogue, which quite frankly could have come from some playground encounter as the kiddies play kiss chase or bang bang your dead army. There's also a sense of familiarity with other better scripted film's, Dances *cough* With *cough* Wolves *cough* It's as if Cameron just knew that narrative structure wasn't as important as having the expensive gimmicks. He's like a modern day William Castle-only with considerably more readies at his disposal.

The cast are OK, Zoe Saldana puts a sexy feistiness to her blue alien Neytiri, Sam Worthington keeps the humanistic elements just about above water, while Sigourney Weaver is as ever the consummate professional. But ironically, in a film shimmering bright in 2d & 3d, the characters are all one dimensional. None more so than Stephen "The Party Crasher" Lang's Colonel. A man so gruff and gung-ho menacing he really ought to be in Sly Stallone's upcoming testo movie The Expendables. Nominated for nine Academy Awards, including Best Picture and Best Director, it won three, for Best Cinematography, Best Visual Effects, and Best Art Direction. Those were richly deserved. They also tell us all we need to now about Cameron's Behemoth. 5/10

In [ ]:
# !pip install transformers
# !pip install torch

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [ ]:
classifier("This movie was absolutely amazing")

[{'label': 'POSITIVE', 'score': 0.9998805522918701}]

In [ ]:
def sentiment_score(reviews):

    if len(reviews) == 0:
        return 0

    scores = []

    for review in reviews:

        result = classifier(review[:512])[0]

        if result['label'] == 'POSITIVE':
            scores.append(result['score'])

        else:
            scores.append(1 - result['score'])

    return sum(scores) / len(scores)

In [ ]:
reviews = fetch_reviews(19995)

score = sentiment_score(reviews)

score

0.9933032035827637

In [ ]:
def hybrid_recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:11]

    final_movies = []

    for i in movies_list:

        idx = i[0]

        similarity_score = i[1]

        movie_id = new_df.iloc[idx].movie_id

        title = new_df.iloc[idx].title

        poster = fetch_poster(movie_id)

        reviews = fetch_reviews(movie_id)

        sentiment = sentiment_score(reviews)

        final_score = (0.8 * similarity_score) + (0.2 * sentiment)

        final_movies.append({
            'title': title,
            'poster': poster,
            'similarity': similarity_score,
            'sentiment': sentiment,
            'final_score': final_score
        })

    final_movies = sorted(
        final_movies,
        reverse=True,
        key=lambda x:x['final_score']
    )

    return final_movies[:5]

In [ ]:
results = hybrid_recommend('Atonement')

In [ ]:
for movie in results:

    print(movie['title'])

    print("Similarity:", movie['similarity'])

    print("Sentiment:", movie['sentiment'])

    print("Final Score:", movie['final_score'])

    print()

Vicky Cristina Barcelona
Similarity: 0.4018460345605143
Sentiment: 0.9983631074428558
Final Score: 0.5211494491369826

Becoming Jane
Similarity: 0.4001107726412816
Sentiment: 0.9716370701789856
Final Score: 0.5144160321488225

The House of Mirth
Similarity: 0.37139067635410367
Sentiment: 0.9907105565071106
Final Score: 0.49525465238470506

The Best of Me
Similarity: 0.36585848168984336
Sentiment: 0.9917272329330444
Final Score: 0.4910322319384836

Anna Karenina
Similarity: 0.42453490440418584
Sentiment: 0.3431583046913147
Final Score: 0.40825958446161165